### ISSUE TITLE
PowerOff HifiBerry

### ISSUE THREAD

**Issue by dgomes** [hifiberry/audiocontrol2#10]
Hi!

I miss an API endpoint to power off my hifiberry.

Would such feature be part of audiocontrol2 ?

(I'm available to work out a PR)

**Comment by hifiberry** [comment]
While I'm not fully convinced that audiocontrol is the right place to implement this, I don't see any better option today. Feel free to prepare a PR for this.
A few comments in advance:
- make sure that the power switch feature is implemented in a separate class to allow easier customisation
- implement some kind of authorisation. Not everybody will be happy with an API that can be used to shut down a system without any authentication/authorisation

**Comment by dgomes** [comment]
any update ?

**Comment by hifiberry** [comment]
Still waiting for your PR

**Comment by dgomes** [comment]
IT's been sitting here: https://github.com/hifiberry/audiocontrol2/pull/11 for the past 21 days :)

**Comment by hifiberry** [comment]
Sorry, I totally missed this.

**Comment by dgomes** [comment]
No problem :)

When is the next scheduled release ?

**Comment by hifiberry** [comment]
Definitely not this year. But you can just copy over the file to your system for now

**Comment by dgomes** [comment]
This has already been integrated :) 

Thank you!
