### ISSUE TITLE
IR - Independent Play / Pause Commands

### ISSUE THREAD

**Issue by Limbo-117** [hifiberry/audiocontrol2#14]
Hello

I see that there is a "playpause" toggle command for the remote - [enter].
Would it be possible to intergrate separate "Play" & "Pause" commands too?
This would make it easier to integrate with universal remotes as you could map these command to the respective key.

So
[up] = play
[down] = pause

A bit like below...

keyboard.py

self.codetable = {
                # volume up
                115: "volume_up",
                 # volume down
                114: "volume_down",
                # right
                106: "next",
                # left
                105: "previous",
                # enter
                28: "playpause",
                # up
                103: "play",
                # down
                108: "pause"
            }

I'm a bit of a noob so editing the .py script and undertaking a buildroot is a bit out of my league.

**Comment by hifiberry** [comment]
This has been implemented with https://github.com/hifiberry/audiocontrol2/commit/99c904bacd0a90f880c01f65129f959c75491ec5
