### ISSUE TITLE
Bidirectional communication API

### ISSUE THREAD

**Issue by schnabel** [hifiberry/audiocontrol2#20]
HI,
I would like to improve the way clients can interact with hifiberry OS. In my case it is the integration into [homeassistant](https://www.home-assistant.io/). Polling the REST API for changes in the audiocontrol state is not the best approach.
It would be great if there was an websocket API. I could try to offer an implementation using [python-socketio](https://github.com/miguelgrinberg/python-socketio).

**Comment by hifiberry** [comment]
Feel free to try and send a pull. As this won't be used by many users, please make sure it's disabled by default and the service will run without this.
Only import additional modules if the websocket API is enabled.

**Comment by schnabel** [comment]
Hi, 
thanks for your interest. My first idea was to integrate the new API with the bottle server [like in this gist](https://gist.github.com/schnabel/a5e0c4aa5f89fee83db505d5df80219a) because python-socketio supports it. That way the footprint would be small.
As I understand you, being able to disable the API and using conditional imports is a MUST. Then I would go for a new daemon thread.

**Comment by hifiberry** [comment]
As audiocontrol is already using bottle, I would not recommend to run a second server on another port. Just extend the existing server, but make sure the additional functionality needs to be enabled in the configuration file.

**Comment by schnabel** [comment]
I am having trouble to test my code :-(. Not sure if a should open a bug report in [hifiberry os](https://github.com/hifiberry/hifiberry-os) or if you can help me here.
I get an error when I try to build the hifiberry-os because of the python keyboard package. It seems to require root privileges because it calls dumpkeys. I tried to add the user I build with to tty and input group as suggested but that did not help. Do you have any idea what to do?

**Comment by hifiberry** [comment]
CHanges have been merged

**Comment by schnabel** [comment]
Thanks a lot!
