### ISSUE TITLE
Ability to toggle bluetooth

### ISSUE THREAD

**Issue by danielriddell21** [hifiberry/audiocontrol2#23]
Hi, I have looked at how you create a plugin. I have worked out how I can integrate this with my buttons and rotary encoders, but I was wondering if there is a way i can toggle bluetooth using a press of the button.

I see there is a send_command() method, is this the correct method to use?

**Comment by hifiberry** [comment]
What do you mean by "toggle bluetooth"?

**Comment by danielriddell21** [comment]
@hifiberry I would like to have a button which can turn on / off bluetooth in HiFiBerryOS. Or a way to disconnect the current connected bluetooth user, similar like you would on a portable speaker

**Comment by hifiberry** [comment]
Audiocontrol isn't designed to interact with hardware in any way. Even with an additional plugin that wouldn't work as there is simply no API for this kind of application.
