### ISSUE TITLE
This would be nice ...

### ISSUE THREAD

**Issue by mbr1989** [hifiberry/audiocontrol2#3]
![IMG-20200228-WA0000](https://user-images.githubusercontent.com/16426506/75582178-4e4ea980-5a6b-11ea-8ec2-55d51ec87c41.jpg)

**Comment by mbr1989** [comment]
Rotary knob for volume ... touchscreen for track control

**Comment by hifiberry** [comment]
Feel free to implement a driver. I don't know the product. My guess is that it's neither cheap nor is the protocol documented.

**Comment by mbr1989** [comment]
I meant that as an idea ... maybe with a 7" raspi touch screen

**Comment by hifiberry** [comment]
It's doable. It would only require a new MetaData display module. Rotary control is already included. IF you want to implement this, let me know. I might be able to improve documentatiif you need some more infos.
