### ISSUE TITLE
REST API Activate player Bug

### ISSUE THREAD

**Issue by fjfricke** [hifiberry/audiocontrol2#30]
In reference to the issue (_Originally posted by @fjfricke in https://github.com/hifiberry/hifiberry-os/issues/393#issuecomment-1262590033_) in the hifiberryOS-Repo:

When trying to activate another player using the REST API, an error message appears.

E.g. `curl -X post http://192.168.1.182:81/api/player/activate/ShairportSync activate/ShairportSync failed with exception 'AudioController' object has no attribute 'mpris_command'% `. It happens with other sources (tried with mpd) as well.

**Comment by fjfricke** [comment]
I tried a few things and found out that it is necessary to include the MPRIS-prefix (`org.mpris.MediaPlayer2.`). Seems to be a small bug?

**Comment by hifiberry** [comment]
If you want to prepare a PULL request, feel free to do.

**Comment by chrisburrc** [comment]
Hi, I'm facing the same issue. I'm running HifiBerry OS 20230223. Was it fixed ultimately and should I make a fresh install? if not, @fjfricke where should the MPRIS-prefix be included, so that I fix it locally.

**Comment by hifiberry** [comment]
As many plqayers do not support any kind of "resume" functionality, we will remove this feature in the future.
