### ISSUE TITLE
GPIO buttons controls

### ISSUE THREAD

**Issue by patrickweigelt** [hifiberry/audiocontrol2#31]
Hi there, Thanks a lot for this excellent system. Is there an example script available on how to trigger some of the audio controls using simple gpio buttons? I managed to get the rotary encoder working and would like to add controls via buttons for next track, previous track, play/pause and stutdown system. Best

**Comment by hifiberry** [comment]
There is no such functionality yet. You would have to create a new plugin for this similar to the rotary controller module:
https://github.com/hifiberry/audiocontrol2/blob/master/ac2/plugins/control/rotary.py
