### ISSUE TITLE
Bluetooth keyboard / remotes cannot reconnect after disconnection

### ISSUE THREAD

**Issue by jkp** [hifiberry/audiocontrol2#35]
When one uses a bluetooth remote (aka keyboard) with the system, things go awry when the device goes to sleep and disconnects. The issue is that in the main loop of the keyboard module there is no handling for the list of input devices being updated....the list is loaded at startup and never updated which means things just break under these circumstances.

I'm using an older version of the code (for other [related reasons](https://github.com/hifiberry/hifiberry-os/issues/480) which I won't describe here to keep things on-topic) where keyboard support is based on the `keyboard` module but reading the latest code it seems like the same issue is present in the rewritten version.

I have put together [a workaround](https://gitlab.com/-/snippets/3613722) based on a bug report to the underlying `keyboard` module that works around the issue in the older version of the code, however someone probably ought to put a fix together in the newer code too. I'd do this but right now it's not possible to get my remote to work at all on the newest hifiberry hence me focussing on a fix for the older version for now.

**Comment by hifiberry** [comment]
We're happy to integrate a patch if you can provide one.
