### ISSUE TITLE
controller and airplay volume

### ISSUE THREAD

**Issue by borkog** [hifiberry/audiocontrol2#36]
Hi,

So I wrote a controller based on an your example here... It works nicely.

1) Problem is Airplay does not get notification when I change volume in my controller. 

2) On every new song Airplay sets it's own volume ... So I get a jump in volume

I did `self.volumecontrol.add_listener(self)` and I get notified when iPhone changes volume, but the problem is that Aiplay forces it's own volume level (becuse problem no.1)

This issue is with latest IOS ... very old IOS do not set volume on song change. 

----
I managed to block Airplay set volume by forcing contoller's own volume level ... but I loose option to change volume over airplay... which is not nice because volume jumps when I try to change it on iPhone

**Comment by hifiberry** [comment]
As this isn't audiocontrol related, I'll close this here. You might try the latest HBOS64 version that comes with the latest shairport-sync. I don't know if this will help with your issue. 
https://github.com/hifiberry/hifiberry-os/releases/tag/64alpha7
