### ISSUE TITLE
Post Api Broken

### ISSUE THREAD

**Issue by Gegreenpeaced** [hifiberry/audiocontrol2#37]
Hey, I have a feeling that the documentation for the Api is outdated.

I tried downloading the metadata and to pause/unpause audio, but I always get an error.
When I use Hifiberrys experimental "Interact" Funktion, it works flawless.

If I'm missing something or somebody has up to day documentation I would be very thankfull.

**Comment by hifiberry** [comment]
The API hasn't changed. It would be a good idea to describe your issue a bit more than "I always get an error"

**Comment by Gegreenpeaced** [comment]
Ok, so the problem wasn't that the API changed but rather that the port to comunicate is 81 instead of 80. Bit stupid by me but I submitted some changes to better understand the API.
