### ISSUE TITLE
socketIO web server not beeing started anymore

### ISSUE THREAD

**Issue by hifiberry** [hifiberry/audiocontrol2#39]
@schnabel Some users have reported that the system doesn't work anymore when SocketIO is enabled. I have a quick look at this. I can only see that the web server can't be started as the address is already in use. It looks the webserver is started twice when enabling the SocketIO variant.

Can you have a look. As base, use HiFiBerryOS64 alpha version as this includes newer versions of Python and probably many modules. The guess is that this is caused by some changed behaviour of a module.

INFO: audiocontrol2 - Ignoring player
INFO: webserver - start server 1
INFO: webserver - starting SocketIO web server
Bottle v0.12.25 server starting up (using GeventServer(handler_class=<class 'geventwebsocket.handler.WebSocketHandler'>))...
Listening on http://0.0.0.0:81/
Hit Ctrl-C to quit.

--- Logging error ---
Traceback (most recent call last):
  File "/opt/audiocontrol2/ac2/webserver.py", line 175, in startServer
    run(self.socketio_api.app,
  File "/usr/lib/python3.11/site-packages/bottle.py", line 3175, in run
  File "/usr/lib/python3.11/site-packages/bottle.py", line 2963, in run
  File "/usr/lib/python3.11/site-packages/gevent/baseserver.py", line 398, in serve_forever
  File "/usr/lib/python3.11/site-packages/gevent/baseserver.py", line 336, in start
  File "/usr/lib/python3.11/site-packages/gevent/pywsgi.py", line 1545, in init_socket
  File "/usr/lib/python3.11/site-packages/gevent/server.py", line 180, in init_socket
  File "/usr/lib/python3.11/site-packages/gevent/server.py", line 192, in get_listener
  File "/usr/lib/python3.11/site-packages/gevent/server.py", line 288, in _tcp_listener
  File "/usr/lib/python3.11/site-packages/gevent/_socketcommon.py", line 563, in bind
OSError: [Errno 98] Address already in use: ('0.0.0.0', 81)

**Comment by schnabel** [comment]
I will have a look at it. But please be patient :-) I don't have too much time these days.

**Comment by hifiberry** [comment]
No problem. We don't have this enabled by default but it seems some users want to use it.

**Comment by hifiberry** [comment]
But: It seems, the socketio server is enabled just if the keyword exists in the config, independent of the value (true, false).

**Comment by schnabel** [comment]
I guess that is because it is python :-). True and False should work! But I will test it.

**Comment by hifiberry** [comment]
It looks like you're just checking if it is defined, not what value it has

"if self.socketio_api is None:"

**Comment by schnabel** [comment]
The problem starts here:
        if config.get("webserver", "socketio_enabled", fallback=False):
            init_socketio_api(server)
Not sure what configparser does. But I will look at it.

**Comment by schnabel** [comment]
It just takes some time because I have to set up the dev environment.

**Comment by hifiberry** [comment]
No need to rush. Thanks

**Comment by schnabel** [comment]
Could you check if the problem exists if you run the webserver on an unprivileged port?

**Comment by schnabel** [comment]
I tried the alpha64 image with port 8181. I am able to connect from homeassistant via socketio.

**Comment by schnabel** [comment]
Hi, I did some more digging. I used the alpha64 image. If socketio_enabled=True the audiocontrol2 runs but the beocreate2 service has a problem.

Mar 20 10:19:48 hifiberry node[1153]: /usr/lib/node_modules/node-fetch/lib/index.js:1461
Mar 20 10:19:48 hifiberry node[1153]:                         reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
Mar 20 10:19:48 hifiberry node[1153]:                                ^
Mar 20 10:19:48 hifiberry node[1153]: FetchError: request to http://127.0.1.1:81/api/track/metadata failed, reason: socket hang up
Mar 20 10:19:48 hifiberry node[1153]:     at ClientRequest.<anonymous> (/usr/lib/node_modules/node-fetch/lib/index.js:1461:11)
Mar 20 10:19:48 hifiberry node[1153]:     at ClientRequest.emit (node:events:514:28)
Mar 20 10:19:48 hifiberry node[1153]:     at Socket.socketOnEnd (node:_http_client:519:9)
Mar 20 10:19:48 hifiberry node[1153]:     at Socket.emit (node:events:526:35)
Mar 20 10:19:48 hifiberry node[1153]:     at endReadableNT (node:internal/streams/readable:1408:12)
Mar 20 10:19:48 hifiberry node[1153]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
Mar 20 10:19:48 hifiberry node[1153]:   type: 'system',
Mar 20 10:19:48 hifiberry node[1153]:   errno: 'ECONNRESET',
Mar 20 10:19:48 hifiberry node[1153]:   code: 'ECONNRESET'
Mar 20 10:19:48 hifiberry node[1153]: }
Mar 20 10:19:48 hifiberry node[1153]: Node.js v20.9.0
Mar 20 10:19:48 hifiberry systemd[1]: beocreate2.service: Main process exited, code=exited, status=1/FAILURE
Mar 20 10:19:48 hifiberry systemd[1]: beocreate2.service: Failed with result 'exit-code'.

I tried curl, python requests and node with a fetch call. All three methods got a valid response without any problem.

**Comment by hifiberry** [comment]
You don't get "OSError: [Errno 98] Address already in use: ('0.0.0.0', 81)" when starting the server?

**Comment by schnabel** [comment]
No. Are you trying to start a second audiocontrol?

**Comment by schnabel** [comment]
I use a fresh image. Do the setup and change the config via ssh and reboot.

**Comment by hifiberry** [comment]
No. Only a single audiocontrol process. I need to look into this again.

**Comment by schnabel** [comment]
Could you try to install the current bugfix of the 2.6 node-fetch. I tried node-fetch@2.6.13. beo-server starts without a problem on my system.

**Comment by hifiberry** [comment]
Not yet, but thanks for the info. I'll look into this, but need to integrate some other stuff first.
