### ISSUE TITLE
This is actually not an issue...

### ISSUE THREAD

**Issue by dubaleeiro** [hifiberry/audiocontrol2#4]
Hi, could you please give me some basic hints to implement a rotary encoder to control the media (previous and next track)?
Thank you !

**Comment by hifiberry** [comment]
https://github.com/hifiberry/audiocontrol2/blob/master/doc/rotary-controller-plugin.md

**Comment by dubaleeiro** [comment]
sorry but I couldn't understand what is actually to be configured. The file ` /etc/audiocontrol2.conf` has been configured successfully, but what exactly should I coy to ` /data/ac2plugins`? Should I create the folder  `ac2plugins`? It doesn't exist in my HifiberryOS installation - I am using Raspi 3 + Hifiberry Amp2.
Thank you!
