### ISSUE TITLE
API error?

### ISSUE THREAD

**Issue by kmplngj** [hifiberry/audiocontrol2#5]
Hello,

I try to implement a component for my home automation but the API does not work for me.

I have a fresh HifiBerry OS installation that is working. (no HifiBerry card today, I want to see if I could make use of the API and wait for the Hifiberry mic ;) )

When I do a curl `http://192.168.188.64:/api/track/metadata` I only the an error.

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/player/status</pre>
</body>
</html>
```

What is wrong?

Thanks!

**Comment by hifiberry** [comment]
On HiFiBerryOS, audiocontrol runs on port 81, not 80.

**Comment by kmplngj** [comment]
Ah that  is easy.

Perhaps it should be mentioned in the doc 😄 

https://github.com/hifiberry/audiocontrol2/blob/master/doc/api.md 

Thanks.
