### ISSUE TITLE
 Bug in API volume adjustment by 1%

### ISSUE THREAD

**Issue by kai-roger** [hifiberry/audiocontrol2#6]
Hi.

I use Node Red for automating a Beocreate board. I increase the volume by +1% with this: {"percent":"+1"}

I started increasing the volume 1% at a time. Starting from 0%.

When I reach 57% volume, the volume stops increasing.

If I manually set the volume to 57%, and try to increase på 1%, the volume won’t increase

If I manually set the volume to 58%, and try to increase på 1%, the volume won’t increase

If I manually set the volume to 59%, and try to increase på 1%, the volume increases 1% for each time as I would expect and all the way to 100%.

When I try to decrease the volume by -1% downwards {"percent":"-1"}, then I see it decreases like this:

60

59

58

Skips 57% and 56%

55

54

53

Etc.

Seems like 56%, 57% and 58% volume have some kind of bug

**Comment by hifiberry** [comment]
Ok, I can confirm this, but it's not a audiocontrol bug, but a problem in dsptoolkit that's doing the volume control for the DSP (probably seom rounding issue). I'll close this here and will open a new bug for DSP Topolkit.

**Comment by hifiberry** [comment]
https://github.com/hifiberry/hifiberry-dsp/issues/14

**Comment by hifiberry** [comment]
After lots of debugging, I finally found the root cause: It's the music player daemon MPD. It seems to use some internal rounding and updates on ALSA creating this problem.
There are 2 things you can do:
1. Disable mpd under General/Music Player Daemon
2. Use larger steps of at least 3%

I'm not sure if this can be fixed easily in MPD

**Comment by hifiberry** [comment]
Here we go:
https://github.com/MusicPlayerDaemon/MPD/issues/822
