### ISSUE TITLE
Beocreate optical input status - API (or automatic muting of optical)

### ISSUE THREAD

**Issue by kai-roger** [hifiberry/audiocontrol2#7]
**Is your feature request related to a problem? Please describe.**
"IP/api/track/metadata" or "IP/api/player/status" is not showing if the optical input is active or not.
It is not possible to stop (temporary mute) the optical input.

**Describe the solution you'd like**
To be able to fetch the optical input status in the API, and be able to mute the input. I can see the optical status in the HifiBerry OS GUI.

**Describe alternatives you've considered**
Built in automatic mute (with automatic mute reset) of the optical input when starting a Spotify streaming to avoid 2 sources playing simultaineously. This is something i have on my Sonos amps.

**Comment by hifiberry** [comment]
While it's theoretically possible, this would require a completely new backend for the DSP. 
Auto-MUTE is integrated into our DSP profiles, but it's designed to work the other way: a signal on optical input will mute other sources on the Pi.

**Comment by kai-roger** [comment]
Hi. Ok. What about a possibility to POST API optical mute/stop? I can then make my own automation in Node Red.

**Comment by hifiberry** [comment]
It's the same. As this has to be handled directly on the DSP this will require a new backend.

**Comment by kai-roger** [comment]
Ok. Is it possible to get the status of the optical? active/inactive APi for presentation on touchpanels? This status is already showing in the GUI.

**Comment by hifiberry** [comment]
You can use the SPDIF register for this. Have a look at the profile that you're using:

`<metadata type="readSPDIFOnRegister">93</metadata>`

You can read this register using dsp-toolkit:

https://github.com/hifiberry/hifiberry-dsp/blob/master/doc/dsptoolkit.md
